### ISSUE TITLE
Search result record chip

### ISSUE THREAD

**Issue by Blagoja95** [Blagoja95/DashNET#44]
@ogi1998  can you provide  colors for search records chip ?

![Image](https://github.com/Blagoja95/DashNET/assets/33908472/702019b1-0301-4824-ab57-4dad88e98df2)

**Comment by ogi1998** [comment]
Colors have been provided on following link: [Link](https://www.figma.com/file/5gYGYXs1BT93FdimScGZBo/DashNET?type=design&node-id=130%3A2&mode=design&t=LaCCXfcvL1GMtDm9-1)

**Comment by Blagoja95** [comment]
@ogi1998 Provide colors for search result chips (see image above)
