### ISSUE TITLE
Define DB tabels

### ISSUE THREAD

**Issue by Blagoja95** [Blagoja95/DashNET#9]
Define:

- [x] task
- [x] comment
- [x] user
- [x] team
- [x] team members and users teams [(tables)](https://stackoverflow.com/a/17371788)

https://www.figma.com/file/5gYGYXs1BT93FdimScGZBo/DashNET?type=design&node-id=3%3A2&mode=design&t=xWrllRSBxela4wcS-1

**Comment by ogi1998** [comment]
Looks good.
